name: Java CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11, bruh why
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('build.gradle') }}
    - name: Build with Gradle
      run: ./gradlew build --no-daemon --max-workers 1
    - name: Upload build artifacts
      uses: actions/upload-artifact@v1
      with:
        name: build-artifacts
        path: build/libs
